# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-13 23:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_three', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post',
            new_name='posts',
        ),
    ]
