# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-07-13 23:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_three', '0002_auto_20190713_2336'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='posts',
            new_name='post',
        ),
    ]
